#   A basic travis.yml boilerplate for Django projects
#	Source: https://gist.github.com/ndarville/3625246

language: python

python:
  - 3.5.2

services: postgresql

env:
  - DJANGO=1.10.2

before_install:
  - export DJANGO_SETTINGS_MODULE=enqueuer_api.settings
  - export PYTHONPATH=$HOME/builds/falcaopetri/enqueuer_api
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate
