# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161024_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
