# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161030_2135'),
        ('api', '0009_merge_20161031_1057'),
    ]

    operations = [
    ]
